### ISSUE TITLE
Safari Bug

### ISSUE THREAD

**Issue by ProjectBay** [analogjs/analog#316]
### Please provide the environment you discovered this bug in.

Safari Browser (Version 15.3 (17612.4.9.1.8))

### Which area/package is the issue in?

create-analog

### Description

When creating and bootstraping a new analog project, an error appears inside the safari console.
The initial project with the counter doesn't work also because of the js error.

### Please provide the exception or error you saw

```true
[Error] SyntaxError: Unexpected token '{'
	promiseReactionJob
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by goetzrobin** [comment]
Seems like its related to https://github.com/analogjs/analog/issues/202

**Comment by goetzrobin** [comment]
@ProjectBay this is an issue for the current development server. I want to point out that this issue is development only and the necessary transformations are applied during the build process!

Here is the commit message from the initial issue:

Angular's compilation results use static blocks by default.
These static blocks are not supported by Safari or other webkit based browsers.
https://caniuse.com/mdn-javascript_classes_static_initialization_blocks
We need to use babel transformations to make the output compatible with iOS if we
want to support them.

Currently, this is only applied to the build output because it significantly alters development experience when applied
every time you make changes to your source files.

Please let me know if this helps!

**Comment by ProjectBay** [comment]
@goetzrobin Yes it helped very much thank you!
When I create a build and run the node server manually safari works perfectly.

**Comment by goetzrobin** [comment]
@ProjectBay I closed the issue for now. We should probably add a note in the documentation about this current limitation, but since the build outputs work in WebKit based browsers supporting them for development is currently not worth the performance hit and significant negative impact on DX.
