### ISSUE TITLE
Feature: add migration to content package for new marked dependencies.

### ISSUE THREAD

**Issue by brandonroberts** [analogjs/analog#490]
We'll need to add a migration for the new marked dependencies to existing projects.

"marked-gfm-heading-id": "^3.0.4"
"marked-highlight": "^2.0.1",

Guide https://nx.dev/packages/plugin/generators/migration

_Originally posted by @brandonroberts in https://github.com/analogjs/analog/pull/487#issuecomment-1612310351_

**Comment by luishcastroc** [comment]
I might be able to take this one, should I update as well the nx/plugin for version 16? I see from there is where the `marked` increase version to `^5.0.2` so maybe add the new dependencies in there as well? honestly first time I'll try that out so want to be sure on what would be the best option. by reading a little bit didn't found a lot on generating the actual migration or how to test it out since this one only adds dependencies doesn't need a generator (it seems).

**Comment by brandonroberts** [comment]
Ok, great. Yes, the Nx plugin would need to be updated also with the updated/new dependencies. A migration is basically a special type of generator
