### ISSUE TITLE
Docs: add deployment guide for Vercel

### ISSUE THREAD

**Issue by brandonroberts** [analogjs/analog#493]
### Which scope/s are relevant/related to the feature request?

Docs

### Information

Analog supports deploying to Vercel through a client-only app or SSR app deployed as a Vercel function.

If you want to deploy a fullstack app, you need to adjust the output directory to use Vercel's Build Output API, which is located in the `.vercel` directory at the root of the workspace.

Here's an example repo https://github.com/brandonroberts/analog-angular-vercel-example

We should document deploying to Vercel with minimal configuration

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by cskiwi** [comment]
@goetzrobin I had to deploy one to vercel, This is like as you mentioned zero config. I've added the "steps", just for reference if anyone is researching before trying it out.

There was a small "issue" I've encountered when using nx build cache, it re-uses it on production build, putting the files in the wrong location because locally the vercel preset wasn't loaded. 


All Can be found in the Pr #544
