### ISSUE TITLE
Children elements in components with ng-content

### ISSUE THREAD

**Issue by JesseRobinsonDev** [analogjs/analog#85]
### Which scope/s are relevant/related to the feature request?

astro-angular

### Information

Unable to render child elements in Angular components using <ng-content></ng-content>

Button component that I want to render children inside the button
Button.ts:
```
import { Component } from "@angular/core";

@Component({
  standalone: true,
  template: `<button><ng-content></ng-content></button>`,
  styles: [],
})
export default class Button {}
```

index.astro:
```
---
import Layout from "../layouts/Layout.astro";
import Button from "../components/button/Button";
---

<Layout title="Astro">
  <Button><span>Click Me!</span></Button>
</Layout>
```

Unsure if there is a specific thing I need to import on the component, I've tried looking around but I can't find anything, wondering if anyone here can provide some insight

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Because of the way the components work with Angular in Astro, I'm not sure this is possible. On the server side, we are rendering the component similar to SSR, so the child content isn't `ng-content` as you'd expect with a normal component. Have to dig further into this to see if there's a solution.

**Comment by brandonroberts** [comment]
Seems like there is a workaround in place for this
